export const demoPuzzles = [
    {
      id: 1,
      name: "Classic Hollywood",
      tiles: [
        { id: 0, type: "Actor", data: { name: "Humphrey Bogart" } },
        { id: 1, type: "Movie", data: { title: "Casablanca" } },
        { id: 2, type: "Actor", data: { name: "Ingrid Bergman" } },
        { id: 3, type: "Movie", data: { title: "Citizen Kane" } },
        { id: 4, type: "Actor", data: { name: "Orson Welles" } },
        { id: 5, type: "Movie", data: { title: "Gone with the Wind" } },
        { id: 6, type: "Actor", data: { name: "Vivien Leigh" } },
        { id: 7, type: "Movie", data: { title: "The Wizard of Oz" } },
        { id: 8, type: "Actor", data: { name: "Judy Garland" } },
        { id: 9, type: "Movie", data: { title: "Singin' in the Rain" } },
        { id: 10, type: "Actor", data: { name: "Gene Kelly" } },
        { id: 11, type: "Movie", data: { title: "Vertigo" } },
        { id: 12, type: "Actor", data: { name: "James Stewart" } },
        { id: 13, type: "Movie", data: { title: "Psycho" } },
        { id: 14, type: "Actor", data: { name: "Anthony Perkins" } },
        { id: 15, type: "Movie", data: { title: "It's a Wonderful Life" } },
        { id: 16, type: "Actor", data: { name: "Donna Reed" } },
        { id: 17, type: "Movie", data: { title: "Sunset Boulevard" } },
        { id: 18, type: "Actor", data: { name: "Gloria Swanson" } },
        { id: 19, type: "Movie", data: { title: "Some Like It Hot" } },
        { id: 20, type: "Actor", data: { name: "Marilyn Monroe" } },
      ],
      initialPlacements: [
        { tileId: 0, position: "0-0" },
        { tileId: 1, position: "0-2" },
      ]
    },
    {
      id: 2,
      name: "Sci-Fi Spectacular",
      tiles: [
        { id: 0, type: "Actor", data: { name: "Harrison Ford" } },
        { id: 1, type: "Movie", data: { title: "Blade Runner" } },
        { id: 2, type: "Actor", data: { name: "Sigourney Weaver" } },
        { id: 3, type: "Movie", data: { title: "Alien" } },
        { id: 4, type: "Actor", data: { name: "Keanu Reeves" } },
        { id: 5, type: "Movie", data: { title: "The Matrix" } },
        { id: 6, type: "Actor", data: { name: "Carrie Fisher" } },
        { id: 7, type: "Movie", data: { title: "Star Wars: A New Hope" } },
        { id: 8, type: "Actor", data: { name: "Mark Hamill" } },
        { id: 9, type: "Movie", data: { title: "2001: A Space Odyssey" } },
        { id: 10, type: "Actor", data: { name: "Sam Rockwell" } },
        { id: 11, type: "Movie", data: { title: "Moon" } },
        { id: 12, type: "Actor", data: { name: "Jodie Foster" } },
        { id: 13, type: "Movie", data: { title: "Contact" } },
        { id: 14, type: "Actor", data: { name: "Will Smith" } },
        { id: 15, type: "Movie", data: { title: "I, Robot" } },
        { id: 16, type: "Actor", data: { name: "Scarlett Johansson" } },
        { id: 17, type: "Movie", data: { title: "Her" } },
        { id: 18, type: "Actor", data: { name: "Chris Pratt" } },
        { id: 19, type: "Movie", data: { title: "Guardians of the Galaxy" } },
        { id: 20, type: "Actor", data: { name: "Zoe Saldana" } },
      ],
      initialPlacements: [
        { tileId: 2, position: "2-1" },
        { tileId: 3, position: "2-2" },
      ]
    },
    {
      id: 3,
      name: "Comedy Classics",
      tiles: [
        { id: 0, type: "Actor", data: { name: "Bill Murray" } },
        { id: 1, type: "Movie", data: { title: "Groundhog Day" } },
        { id: 2, type: "Actor", data: { name: "Melissa McCarthy" } },
        { id: 3, type: "Movie", data: { title: "Bridesmaids" } },
        { id: 4, type: "Actor", data: { name: "Jim Carrey" } },
        { id: 5, type: "Movie", data: { title: "Dumb and Dumber" } },
        { id: 6, type: "Actor", data: { name: "Kristen Wiig" } },
        { id: 7, type: "Movie", data: { title: "Anchorman" } },
        { id: 8, type: "Actor", data: { name: "Will Ferrell" } },
        { id: 9, type: "Movie", data: { title: "Superbad" } },
        { id: 10, type: "Actor", data: { name: "Emma Stone" } },
        { id: 11, type: "Movie", data: { title: "Mean Girls" } },
        { id: 12, type: "Actor", data: { name: "Lindsay Lohan" } },
        { id: 13, type: "Movie", data: { title: "The Hangover" } },
        { id: 14, type: "Actor", data: { name: "Zach Galifianakis" } },
        { id: 15, type: "Movie", data: { title: "Shaun of the Dead" } },
        { id: 16, type: "Actor", data: { name: "Simon Pegg" } },
        { id: 17, type: "Movie", data: { title: "Airplane!" } },
        { id: 18, type: "Actor", data: { name: "Leslie Nielsen" } },
        { id: 19, type: "Movie", data: { title: "This Is Spinal Tap" } },
        { id: 20, type: "Actor", data: { name: "Christopher Guest" } },
      ],
      initialPlacements: [
        { tileId: 1, position: "4-0" },
        { tileId: 4, position: "4-4" },
      ]
    }
  ];