export const demoPuzzles = [
    {
      id: 1,
      name: "Classic Hollywood",
      tiles: [
        { id: 0, type: "Actor", data: { name: "Humphrey Bogart" } },
        { id: 1, type: "Movie", data: { title: "Casablanca" } },
        { id: 2, type: "Actor", data: { name: "Ingrid Bergman" } },
        { id: 3, type: "Movie", data: { title: "Citizen Kane" } },
        { id: 4, type: "Actor", data: { name: "Orson Welles" } },
        { id: 5, type: "Movie", data: { title: "Gone with the Wind" } },
        { id: 6, type: "Actor", data: { name: "Vivien Leigh" } },
        { id: 7, type: "Movie", data: { title: "The Wizard of Oz" } },
        { id: 8, type: "Actor", data: { name: "Judy Garland" } },
        { id: 9, type: "Movie", data: { title: "Singin' in the Rain" } },
        { id: 10, type: "Actor", data: { name: "Gene Kelly" } },
        { id: 11, type: "Movie", data: { title: "Vertigo" } },
        { id: 12, type: "Actor", data: { name: "James Stewart" } },
        { id: 13, type: "Movie", data: { title: "Psycho" } },
        { id: 14, type: "Actor", data: { name: "Anthony Perkins" } },
        { id: 15, type: "Movie", data: { title: "It's a Wonderful Life" } },
        { id: 16, type: "Actor", data: { name: "Donna Reed" } },
        { id: 17, type: "Movie", data: { title: "Sunset Boulevard" } },
        { id: 18, type: "Actor", data: { name: "Gloria Swanson" } },
        { id: 19, type: "Movie", data: { title: "Some Like It Hot" } },
        { id: 20, type: "Actor", data: { name: "Marilyn Monroe" } },
      ],
      initialPlacements: [
        { tileId: 1, position: "0-0" },
        { tileId: 0, position: "0-1" },
      ],
      solution: [
        [1, 0, 3, 2, 5],
        [4, null, 8, null, 12],
        [7, 6, 9, 10, 11],
        [14, null, 16, null, 18],
        [13, 20, 15, 17, 19]
      ]
    },
    {
      id: 2,
      name: "Modern Blockbusters",
      tiles: [
        { id: 0, type: "Actor", data: { name: "Robert Downey Jr." } },
        { id: 1, type: "Movie", data: { title: "Iron Man" } },
        { id: 2, type: "Actor", data: { name: "Chris Evans" } },
        { id: 3, type: "Movie", data: { title: "Captain America: The First Avenger" } },
        { id: 4, type: "Actor", data: { name: "Scarlett Johansson" } },
        { id: 5, type: "Movie", data: { title: "Black Widow" } },
        { id: 6, type: "Actor", data: { name: "Chris Hemsworth" } },
        { id: 7, type: "Movie", data: { title: "Thor" } },
        { id: 8, type: "Actor", data: { name: "Mark Ruffalo" } },
        { id: 9, type: "Movie", data: { title: "The Avengers" } },
        { id: 10, type: "Actor", data: { name: "Tom Holland" } },
        { id: 11, type: "Movie", data: { title: "Spider-Man: Homecoming" } },
        { id: 12, type: "Actor", data: { name: "Chadwick Boseman" } },
        { id: 13, type: "Movie", data: { title: "Black Panther" } },
        { id: 14, type: "Actor", data: { name: "Brie Larson" } },
        { id: 15, type: "Movie", data: { title: "Captain Marvel" } },
        { id: 16, type: "Actor", data: { name: "Benedict Cumberbatch" } },
        { id: 17, type: "Movie", data: { title: "Doctor Strange" } },
        { id: 18, type: "Actor", data: { name: "Elizabeth Olsen" } },
        { id: 19, type: "Movie", data: { title: "WandaVision" } },
        { id: 20, type: "Actor", data: { name: "Paul Rudd" } },
      ],
      initialPlacements: [
        { tileId: 1, position: "0-0" },
        { tileId: 0, position: "0-1" },
      ],
      solution: [
        [1, 0, 3, 2, 5],
        [4, null, 7, null, 6],
        [9, 8, 11, 10, 13],
        [12, null, 15, null, 14],
        [17, 16, 19, 18, 20]
      ]
    },
    {
      id: 3,
      name: "Oscar Winners",
      tiles: [
        { id: 0, type: "Actor", data: { name: "Frances McDormand" } },
        { id: 1, type: "Movie", data: { title: "Nomadland" } },
        { id: 2, type: "Actor", data: { name: "Anthony Hopkins" } },
        { id: 3, type: "Movie", data: { title: "The Father" } },
        { id: 4, type: "Actor", data: { name: "Joaquin Phoenix" } },
        { id: 5, type: "Movie", data: { title: "Joker" } },
        { id: 6, type: "Actor", data: { name: "Renée Zellweger" } },
        { id: 7, type: "Movie", data: { title: "Judy" } },
        { id: 8, type: "Actor", data: { name: "Olivia Colman" } },
        { id: 9, type: "Movie", data: { title: "The Favourite" } },
        { id: 10, type: "Actor", data: { name: "Rami Malek" } },
        { id: 11, type: "Movie", data: { title: "Bohemian Rhapsody" } },
        { id: 12, type: "Actor", data: { name: "Gary Oldman" } },
        { id: 13, type: "Movie", data: { title: "Darkest Hour" } },
        { id: 14, type: "Actor", data: { name: "Emma Stone" } },
        { id: 15, type: "Movie", data: { title: "La La Land" } },
        { id: 16, type: "Actor", data: { name: "Casey Affleck" } },
        { id: 17, type: "Movie", data: { title: "Manchester by the Sea" } },
        { id: 18, type: "Actor", data: { name: "Brie Larson" } },
        { id: 19, type: "Movie", data: { title: "Room" } },
        { id: 20, type: "Actor", data: { name: "Leonardo DiCaprio" } },
      ],
      initialPlacements: [
        { tileId: 1, position: "0-0" },
        { tileId: 0, position: "0-1" },
      ],
      solution: [
        [1, 0, 3, 2, 5],
        [4, null, 7, null, 6],
        [9, 8, 11, 10, 13],
        [12, null, 15, null, 14],
        [17, 16, 19, 18, 20]
      ]
    }
  ];